### ISSUE TITLE
Make this private

### ISSUE THREAD

**Issue by De-ma** [zinabat/CIS2430_A1#1]
Hey, I don't know who you are, but GitHub has a free unlimited amount of private repo's for students, and having your code for CIS classes public is academic misconduct! I would hate anything to happen to you because of this dumb thing, just thought you should know!!! 

How to register as a student: https://education.github.com/pack 

-Fellow 2430 classmate

**Comment by zinabat** [comment]
Thanks, I couldn't figure out how to set up a student account.
